name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Use Cypress GitHub action to run tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
